config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  resources :atolyelers
  resources :products
  root to: 'pages#home'
  get '/iletisim', to: 'pages#iletisim'
  get '/kimdir', to: 'pages#kimdir'
  get '/referanslar', to: 'pages#referanslar'


  resources :satinals, only: [:index, :show]
  resources :orders, only: [:show, :create] do
  resources :payments, only: [:new, :create]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atolyeler.rb
class Atolyeler < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :amount_cents
end

app/models/product.rb
class Product < ApplicationRecord
  attr_accessor :new_category_name
  belongs_to :category, required: false
  before_save :create_category_from_name
  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end
end

app/models/satinal.rb
class Satinal < ApplicationRecord
   monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/atolyelers_controller.rb
class AtolyelersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_atolyeler, only: [:show, :edit, :update, :destroy]

  def index
    @atolyelers = policy_scope(Atolyeler).order(created_at: :desc)
  end

  def show
    authorize @atolyeler
  end

  def new
    @atolyeler = Atolyeler.new
  end

  def edit
  end

  def create
    @atolyeler = Atolyeler.new(atolyeler_params)
      if @atolyeler.save
        redirect_to @atolyeler, notice: 'Atolyeler was successfully created.'
      else
        render :new
      end
  end

  def update
    if @atolyeler.update(atolyeler_params)
      redirect_to @atolyeler, notice: 'Atolyeler was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @atolyeler.destroy
      redirect_to atolyelers_url, notice: 'Atolyeler was successfully destroyed.'
    end
  end

  private

  def set_atolyeler
    @atolyeler = Atolyeler.find(params[:id])
  end

  def atolyeler_params
    params.require(:atolyeler).permit(:picture_url)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!
  def create
    satinal = Satinal.find(params[:satinal_id])
    order = Order.create!(satinal_sku: satinal.sku, amount: satinal.price, state: 'pending', user: current_user)

    redirect_to new_order_payment_path(order)
    authorize order
  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
    authorize @order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :referanslar, :kimdir, :iletisim]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_order

  def new
     authorize @order
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for teddy #{@order.satinal_sku} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to order_path(@order)
    authorize @order
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    authorize @order

  end
end
    # @products = policy_scope(Order).where(state: 'pending', user_id: current_user.id).find(params[:order_id])

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = policy_scope(Product).order(created_at: :desc)
  end

  def new
    @product = Product.new
  end

  def create
    ## TO DO: when categories is created and tags add it to params
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
  end

  def edit
  end

  def update
    if @product.update
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :category_id, :new_category_name)
  end
end

app/controllers/satinals_controller.rb
class SatinalsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @satinals = Satinal.all
    @satinals = policy_scope(Satinal).order(created_at: :desc)
  end

  def show
    @satinal = Satinal.find(params[:id])
    authorize @satinal
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/atolyelers/_form.html.erb
<%= simple_form_for(@atolyeler) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :picture_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/atolyelers/edit.html.erb
<h1>Editing Atolyeler</h1>

<%= render 'form', atolyeler: @atolyeler %>

<%= link_to 'Show', @atolyeler %> |
<%= link_to 'Back', atolyelers_path %>

app/views/atolyelers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atolyelers</h1>

<table>
  <thead>
    <tr>
      <th>Picture url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atolyelers.each do |atolyeler| %>
      <tr>
        <td><%= image_tag atolyeler.picture_url %></td>

        <td><%= link_to 'Show', atolyeler %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/atolyelers/new.html.erb
<h1>New Atolyeler</h1>

<%= render 'form', atolyeler: @atolyeler %>

<%= link_to 'Back', atolyelers_path %>

app/views/atolyelers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture url:</strong>
  <%= @atolyeler.picture_url %>
</p>

<%= link_to 'Back', atolyelers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Nunito+Sans" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster" />
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <%= stylesheet_link_tag    'application', media: 'all', :'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', :'data-turbolinks-track' => 'reload' %>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <div class="basr">
      <div class="text-center">

      </div>
    </div>
    <div class="container text-center">
      <%= yield %>
    </div>
    <footer id="myFooter">
      <div class="container">
        <div class="row">
          <div class="col-sm-3">
            <br>
            <%= image_tag 'footer.png', class: 'logo' %>
          </div>
          <div class="col-sm-3">
            <h5>YARDIM</h5>
            <ul>
              <li><a href="#">Ödeme ve Teslimat</a></li>
              <li><a href="#">Gizlilik ve Kullanım Şartları</a></li>
            </ul>
          </div>
          <div class="col-sm-3">
            <h5></h5>
            <%= image_tag 'ssl.png', class: 'ssl' %>
          </div>
          <div class="col-sm-3">
            <div class="social-networks">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
            </div>
            <button type="button" class="btn btn-default">Contact us</button>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
  <p>© www.makemydaytr.com bulunan tüm ürün ürünlere ait açıklayıcı bilgiler, görseller telif hakları kanununca korunmakta olup izinsiz paylaşılması, kopyalanması veya herhangi biri yazılı ya da görsel mecralarda kullanılması kanunen yasaklanmış olup hukuki yaptırıma tabi tutulmaktadır. </p>
        </div>

      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>

    </body>
  </html>

app/views/orders/show.html.erb
<!-- app/views/orders/show.html.erb -->
<h1>Order</h1>
<ul>
  <li>Status: <%= @order.state %></li>
  <li>Item: <%= @order.satinal_sku %></li>
  <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
<ul>

app/views/pages/home.html.erb
<% content_for :head do %>
<meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="slaytlar text-center">
  <div class="scroller">
    <div><%= image_tag "1.png" %></div>
    <div><%= image_tag "2.png" %></div>
    <div><%= image_tag "3.png" %></div>
    <div><%= image_tag "4.png" %></div>
    <div><%= image_tag "5.png" %></div>
    <div><%= image_tag "6.png" %></div>
    <div><%= image_tag "7.png" %></div>
  </div>
</div>

<div>
  <h3 > <span class="xx">gününüzü güzelleştİrİn</span> <strong>#makemydaytr </strong></h3>
</div>

<div class="biz">
<div class="anacardlar text-center">

  <div class="ancard"><%= image_tag 'kendi1.png' %></div>
  <div class="ancard"><%= image_tag 'kendi2.png' %></div>
  <div class="ancard"><%= image_tag 'kendi3.png' %></div>
  <div class="ancard"><%= image_tag 'kendi4.png' %></div>
  <div class="ancard"><%= image_tag 'kendi5.png' %></div>
  <div class="ancard"><%= image_tag 'kendi6.png' %></div>
  <div class="ancard"><%= image_tag 'kendi7.png' %></div>
  <div class="ancard"><%= image_tag 'kendi8.png' %></div>
  <div class="ancard"><%= image_tag 'kendi9.png' %></div>


</div>
</div>

app/views/pages/iletisim.html.erb
<h1>ILETISIMS</h1>

app/views/pages/kimdir.html.erb
<h1>MAKE MYDAY KIMDIR</h1>

app/views/pages/referanslar.html.erb
<div class="baslik yy">
  <h2>REFERANSLAR</h2>
</div>
<div class="referans">
  <div class="row">
    <div class="col-xs-12 yy">
  <%= image_tag 'referans.png' %>

    </div>
  </div>
</div>

app/views/payments/new.html.erb
<!-- app/views/payments/new.html.erb -->
<h1>Purchase of satinal <%= @order.satinal_sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My satinal"
    data-email="<%= current_user.email %>"
    data-description="satinal <%= @order.satinal_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>

<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <p>
    <label for="product_category_id">Category:</label><br />
    <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "Select a Category" %>
    or create one:
    <%= f.text_field :new_category_name %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<ul>
  <% @products.each do |product|   %>

  <li><%= product.category.name%></li>
  <li><%= product.name %></li>


  <%= link_to 'show', product_path(product) %>





  <% end %>


  </ul>

app/views/products/new.html.erb
 <h1>New product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<ul>
  <li><%= @product.id  %></li>
  <li><%= @product.name  %></li>
  <li><%= @product.category.id %></li>

<%= link_to 'Back', products_path %>


</ul>

app/views/satinals/index.html.erb
<div class="container">
  <div class="row">
    <h1>Atolyeler</h1>
    <% @satinals.each do |satinal| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= link_to image_tag(satinal.photo_url), satinal_path(satinal) %>
          <div class="caption">
            <h3><%= link_to satinal.title, satinal_path(satinal) %></h3>
            <p><%= satinal.location %></p>
            <p>Amount: <%= humanized_money_with_symbol(satinal.price) %></p>
            <p>$$$</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/satinals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @satinal.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= image_tag(@satinal.photo_url, width: '100%') %>
    </div>
    <div class="col-sm-12 col-md-6">
      <p>Some awesome description of our amazing satinal.</p>
      <p><%= @satinal.location %></p>
            <p>Amount: <%= humanized_money_with_symbol(@satinal.price) %></p>

      <p>$$$</p>
      <%= form_tag orders_path do %>
  <%= hidden_field_tag 'satinal_id', @satinal.id %>
  <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
<% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
 <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "header.png" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">

        <li class="nav-item active"><p>

          <%= link_to "ATÖLYELER", atolyelers_path, class: "nav-link" %>
        </p>
        </li>
        <li class="nav-item"><p>

          <%= link_to "ATÖLYE SATIN AL", satinals_path, class: "nav-link" %>
        </p>
        </li>
         <li class="nav-item"><p>

          <%= link_to "AYLIK TAKVİM", products_path, class: "nav-link" %>
         </p>
        </li>
        <li class="nav-item"><p>

          <%= link_to "İLETİŞİM", "/iletisim", class: "nav-link" %>
        </p>
        </li>
        <li class="nav-item"><p>

          <%= link_to "MAKE MY DAY NEDİR?", "/kimdir", class: "nav-link" %>
        </p>
        </li>
        <li class="nav-item"><p>

          <%= link_to "REFERANSLAR", "/referanslar", class: "nav-link" %>
        </p>
        </li>

          <% if user_signed_in? %>
        <li class="nav-item"><p>


            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </p>
        </li>
         <% else %>
        <li class="nav-item"><p>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </p>

        </li>
      <% end %>
        <li class="nav-item dropdown">
          <%= image_tag "header.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "iletisim", "/iletisim", class: "dropdown-item" %>
            <%= link_to "kimdir", "/kimdir", class: "dropdown-item" %>
            <%= link_to "referanslar", "/referanslar", class: "dropdown-item" %>

          </div>
        </li>

    </ul>
  </div>
</div>